package ch.ethz.las.wikimining.mr.influence.h104;

import ch.ethz.las.wikimining.mr.base.Fields;
import ch.ethz.las.wikimining.mr.utils.h104.SetupHelper;
import java.io.IOException;
import java.util.Iterator;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.GnuParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.OptionBuilder;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;
import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapred.JobClient;
import org.apache.hadoop.mapred.JobConf;
import org.apache.hadoop.mapred.MapReduceBase;
import org.apache.hadoop.mapred.OutputCollector;
import org.apache.hadoop.mapred.Reducer;
import org.apache.hadoop.mapred.Reporter;
import org.apache.hadoop.mapred.lib.IdentityMapper;
import org.apache.hadoop.util.Tool;
import org.apache.hadoop.util.ToolRunner;
import org.apache.log4j.Logger;
import org.apache.mahout.math.VectorWritable;

/**
 * Removes duplicates (possibly) generated by TfIdfNovelty.
 *
 * @author Victor Ungureanu (uvictor@student.ethz.ch)
 */
public class TfIdfRemoveDuplicates extends Configured implements Tool {

  private static enum Records {

    TOTAL,
    DUPLICATES
  };

  private static class Reduce extends MapReduceBase implements Reducer<
      Text, VectorWritable, Text, VectorWritable> {

    @Override
    public void reduce(Text docId, Iterator<VectorWritable> docs,
        OutputCollector<Text, VectorWritable> output, Reporter reporter)
        throws IOException {
      reporter.getCounter(Records.TOTAL).increment(1);

      output.collect(docId, docs.next());

      if (docs.hasNext()) {
        reporter.getCounter(Records.DUPLICATES).increment(1);
      }
    }
  }

  private static final Logger logger =
      Logger.getLogger(TfIdfRemoveDuplicates.class);

  private String inputPath;
  private String outputPath;

  public TfIdfRemoveDuplicates() { }

  @Override
  public int run(String[] args) throws Exception {
    final int ret = parseArgs(args);
    if (ret < 0) {
      return ret;
    }

    JobConf config = new JobConf(getConf(), TfIdfRemoveDuplicates.class);
    config.setJobName("Influence-TfIdfRemoveDuplicates");

    SetupHelper.getInstance()
        .setSequenceInput(config, inputPath)
        .setSequenceOutput(config, outputPath);

    config.setMapOutputKeyClass(Text.class);
    config.setMapOutputValueClass(VectorWritable.class);
    config.setOutputKeyClass(Text.class);
    config.setOutputValueClass(VectorWritable.class);

    // Identity Mapper
    config.setMapperClass(IdentityMapper.class);
    config.setReducerClass(Reduce.class);

    // Delete the output directory if it exists already.
    FileSystem.get(getConf()).delete(new Path(outputPath), true);

    JobClient.runJob(config);

    return 0;
  }

  @SuppressWarnings("static-access")
  private int parseArgs(String[] args) {
    Options options = new Options();
    options.addOption(OptionBuilder.withArgName("path").hasArg()
        .withDescription("Duplicate tfidf vectors").create(Fields.INPUT.get()));
    options.addOption(OptionBuilder.withArgName("path").hasArg()
        .withDescription("Unique tfidf vectors").create(Fields.OUTPUT.get()));

    CommandLine cmdline;
    CommandLineParser parser = new GnuParser();
    try {
      cmdline = parser.parse(options, args);
    } catch (ParseException exp) {
      System.err.println("Error parsing command line: " + exp.getMessage());
      return -1;
    }

    if (!cmdline.hasOption(Fields.INPUT.get())
        || !cmdline.hasOption(Fields.OUTPUT.get())) {
      HelpFormatter formatter = new HelpFormatter();
      formatter.printHelp(this.getClass().getName(), options);
      ToolRunner.printGenericCommandUsage(System.out);
      return -1;
    }

    inputPath = cmdline.getOptionValue(Fields.INPUT.get());
    outputPath = cmdline.getOptionValue(Fields.OUTPUT.get());

    logger.info("Tool name: " + this.getClass().getName());
    logger.info(" - input: " + inputPath);
    logger.info(" - output: " + outputPath);

    return 0;
  }

  public static void main(String[] args) throws Exception {
    ToolRunner.run(new TfIdfRemoveDuplicates(), args);
  }
}
